export const ADD_CONTACT = 'ADD_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const FETCHING_CONTACTS = 'FETCHING_CONTACTS';
export const FETCHING_CONTACTS_SUCCESS = 'FETCHING_CONTACTS_SUCCESS';
export const FETCHING_CONTACTS_FAILURE = 'FETCHING_CONTACTS_FAILURE';