export const FETCHING_CONTACTS = 'FETCHING_CONTACTS';
export const FETCHING_CONTACTS_SUCCESS = 'FETCHING_CONTACTS_SUCCESS';
export const FETCHING_CONTACTS_FAILURE = 'FETCHING_CONTACTS_FAILURE';
export const UPLOADING_CONTACT = 'UPLOADING_CONTACT';
export const UPLOADING_CONTACT_SUCCESS = 'UPLOADING_CONTACT_SUCCESS';
export const UPLOADING_CONTACT_FAILURE = 'UPLOADING_CONTACT_FAILURE';